#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use IO::Socket;

my $sock = IO::Socket::INET->new(
    Proto     => 'tcp',
    LocalAddr => '127.0.0.1',
    LocalPort => 12345,
    ReuseAddr => 1,
    Listen    => 1
) or die "couldn't create socket: $!";

while ( my $client = $sock->accept() ) {

    print $client "HELLO 0.1\n";

    my $buffer;
    my $copydata;
    $client->recv( $buffer, 4 );

    # TODO: decide if we want to allow this paste

    do {
        $copydata .= $buffer;
        $client->recv( $buffer, 4 );
    } while ($buffer);

    print STDERR "all data: $copydata\n";

    my $pbcopy;
    open( $pbcopy, "|pbcopy" ) or die "unable to open $!";
    print $pbcopy $copydata;
    close($pbcopy);

    close $client;
}
